# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeightRatioCalculator(object):
    def setupUi(self, WeightRatioCalculator):
        WeightRatioCalculator.setObjectName("WeightRatioCalculator")
        WeightRatioCalculator.resize(540, 300)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        WeightRatioCalculator.setFont(font)
        self.widget = QtWidgets.QWidget(WeightRatioCalculator)
        self.widget.setGeometry(QtCore.QRect(30, 20, 471, 241))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.MF = QtWidgets.QLabel(self.widget)
        self.MF.setObjectName("MF")
        self.gridLayout_4.addWidget(self.MF, 2, 0, 1, 1)
        self.TotalAW = QtWidgets.QLabel(self.widget)
        self.TotalAW.setObjectName("TotalAW")
        self.gridLayout_4.addWidget(self.TotalAW, 1, 0, 1, 2)
        self.Exit = QtWidgets.QPushButton(self.widget)
        self.Exit.setObjectName("Exit")
        self.gridLayout_4.addWidget(self.Exit, 4, 5, 1, 2)
        self.INSP = QtWidgets.QLabel(self.widget)
        self.INSP.setObjectName("INSP")
        self.gridLayout_4.addWidget(self.INSP, 2, 4, 1, 1)
        self.Submit = QtWidgets.QPushButton(self.widget)
        self.Submit.setObjectName("Submit")
        self.gridLayout_4.addWidget(self.Submit, 4, 0, 1, 3)
        self.CAV = QtWidgets.QLineEdit(self.widget)
        self.CAV.setObjectName("CAV")
        self.gridLayout_4.addWidget(self.CAV, 0, 2, 1, 2)
        self.MFV = QtWidgets.QLineEdit(self.widget)
        self.MFV.setObjectName("MFV")
        self.gridLayout_4.addWidget(self.MFV, 2, 2, 1, 2)
        self.CupAW = QtWidgets.QLabel(self.widget)
        self.CupAW.setObjectName("CupAW")
        self.gridLayout_4.addWidget(self.CupAW, 0, 0, 1, 2)
        self.TotalBW = QtWidgets.QLabel(self.widget)
        self.TotalBW.setObjectName("TotalBW")
        self.gridLayout_4.addWidget(self.TotalBW, 1, 4, 1, 2)
        self.CupBW = QtWidgets.QLabel(self.widget)
        self.CupBW.setObjectName("CupBW")
        self.gridLayout_4.addWidget(self.CupBW, 0, 4, 1, 2)
        self.ResultLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setObjectName("ResultLabel")
        self.gridLayout_4.addWidget(self.ResultLabel, 3, 1, 1, 2)
        self.TAV = QtWidgets.QLineEdit(self.widget)
        self.TAV.setObjectName("TAV")
        self.gridLayout_4.addWidget(self.TAV, 1, 2, 1, 2)
        self.CBV = QtWidgets.QLineEdit(self.widget)
        self.CBV.setObjectName("CBV")
        self.gridLayout_4.addWidget(self.CBV, 0, 6, 1, 1)
        self.TBV = QtWidgets.QLineEdit(self.widget)
        self.TBV.setObjectName("TBV")
        self.gridLayout_4.addWidget(self.TBV, 1, 6, 1, 1)
        self.INSPV = QtWidgets.QLineEdit(self.widget)
        self.INSPV.setObjectName("INSPV")
        self.gridLayout_4.addWidget(self.INSPV, 2, 6, 1, 1)
        self.RV = QtWidgets.QTextBrowser(self.widget)
        self.RV.setObjectName("RV")
        self.gridLayout_4.addWidget(self.RV, 3, 3, 1, 4)

        self.retranslateUi(WeightRatioCalculator)
        QtCore.QMetaObject.connectSlotsByName(WeightRatioCalculator)

    def retranslateUi(self, WeightRatioCalculator):
        _translate = QtCore.QCoreApplication.translate
        WeightRatioCalculator.setWindowTitle(_translate("WeightRatioCalculator", "Form"))
        self.MF.setText(_translate("WeightRatioCalculator", "Manufacturer:"))
        self.TotalAW.setText(_translate("WeightRatioCalculator", "Total A Weight (g):"))
        self.Exit.setText(_translate("WeightRatioCalculator", "exit"))
        self.INSP.setText(_translate("WeightRatioCalculator", "Inspection: "))
        self.Submit.setText(_translate("WeightRatioCalculator", "submit"))
        self.CupAW.setText(_translate("WeightRatioCalculator", "Cup A Weight (g): "))
        self.TotalBW.setText(_translate("WeightRatioCalculator", "Total B Weight (g):"))
        self.CupBW.setText(_translate("WeightRatioCalculator", "Cup B Weight (g):"))
        self.ResultLabel.setText(_translate("WeightRatioCalculator", "Result:"))
